# Generated by Django 6.0.3 on 2026-03-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_customer_is_active_historicalcustomer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at']},
        ),
    ]
