# Generated by Django 6.0.3 on 2026-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_is_active_historicalcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
    ]
