# Generated by Django 6.0.3 on 2026-03-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_historicalstock_min_stock_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-created_at']},
        ),
    ]
