# Generated by Django 6.0.3 on 2026-03-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicalproduct_purchase_price_and_more'),
        ('orders', '0006_alter_customer_options_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstockmovement',
            name='order_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='historicalstockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='historicalstockmovement',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.salesorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='orders.salesorder'),
        ),
    ]
